# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QRCode' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'IQKeyboardManagerSwift'
  pod 'KumulosSdkSwift', '~> 4.0'
  pod 'KeychainSwift', '~> 14.0'
  
  target 'QRCodeTests' do
    inherit! :search_paths
    pod 'KumulosSdkSwift', '~> 4.0'
  end

  target 'QRCodeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
